<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-23T16:32:42 IST" name="Suite" finished-at="2024-03-23T16:33:37 IST" duration-ms="55280">
    <groups>
      <group name="Purchase">
        <method signature="rahulShettyWebsiteCases.clientStart(java.util.HashMap)[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" name="clientStart" class="AutomationCasesProject.TestCases.rahulShettyWebsiteCases"/>
      </group> <!-- Purchase -->
      <group name="MouseHover">
        <method signature="rahulShettyWebsiteCases.verifyMouseHover()[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" name="verifyMouseHover" class="AutomationCasesProject.TestCases.rahulShettyWebsiteCases"/>
      </group> <!-- MouseHover -->
    </groups>
    <test started-at="2024-03-23T16:32:42 IST" name="Test" finished-at="2024-03-23T16:33:37 IST" duration-ms="55280">
      <class name="AutomationCasesProject.ExtentReports.ExtentReportsDemo">
        <test-method signature="Demo()[pri:0, instance:AutomationCasesProject.ExtentReports.ExtentReportsDemo@17bffc17]" started-at="2024-03-23T16:32:52 IST" name="Demo" finished-at="2024-03-23T16:32:55 IST" duration-ms="3754" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Demo -->
      </class> <!-- AutomationCasesProject.ExtentReports.ExtentReportsDemo -->
      <class name="AutomationCasesProject.TestCases.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationCasesProject.TestCases.ErrorValidation@3f4faf53]" started-at="2024-03-23T16:32:42 IST" name="launchApplication" finished-at="2024-03-23T16:32:45 IST" duration-ms="2718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="clientStart()[pri:0, instance:AutomationCasesProject.TestCases.ErrorValidation@3f4faf53]" started-at="2024-03-23T16:32:45 IST" name="clientStart" finished-at="2024-03-23T16:32:45 IST" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clientStart -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationCasesProject.TestCases.ErrorValidation@3f4faf53]" started-at="2024-03-23T16:32:45 IST" name="launchApplication" finished-at="2024-03-23T16:32:46 IST" duration-ms="1404" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="verifyMouseHover()[pri:0, instance:AutomationCasesProject.TestCases.ErrorValidation@3f4faf53]" started-at="2024-03-23T16:32:46 IST" name="verifyMouseHover" finished-at="2024-03-23T16:32:52 IST" duration-ms="5236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMouseHover -->
      </class> <!-- AutomationCasesProject.TestCases.ErrorValidation -->
      <class name="AutomationCasesProject.TestCases.rahulShettyWebsiteCases">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" started-at="2024-03-23T16:32:56 IST" name="launchApplication" finished-at="2024-03-23T16:32:59 IST" duration-ms="3045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="clientStart(java.util.HashMap)[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" started-at="2024-03-23T16:32:59 IST" name="clientStart" data-provider="getData" finished-at="2024-03-23T16:33:12 IST" duration-ms="12918" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Akshay123, product=ZARA COAT 3, email=akshay1999@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at AutomationCasesProject.TestCases.rahulShettyWebsiteCases.clientStart(rahulShettyWebsiteCases.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clientStart -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" started-at="2024-03-23T16:33:12 IST" name="launchApplication" finished-at="2024-03-23T16:33:15 IST" duration-ms="2981" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="clientStart(java.util.HashMap)[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" started-at="2024-03-23T16:33:15 IST" name="clientStart" data-provider="getData" finished-at="2024-03-23T16:33:28 IST" duration-ms="13127" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Chikku123!, product=ADIDAS ORIGINAL, email=chikku199@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at AutomationCasesProject.TestCases.rahulShettyWebsiteCases.clientStart(rahulShettyWebsiteCases.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clientStart -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" started-at="2024-03-23T16:33:28 IST" name="launchApplication" finished-at="2024-03-23T16:33:33 IST" duration-ms="4901" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="verifyMouseHover()[pri:0, instance:AutomationCasesProject.TestCases.rahulShettyWebsiteCases@6e535154]" started-at="2024-03-23T16:33:33 IST" name="verifyMouseHover" finished-at="2024-03-23T16:33:37 IST" duration-ms="4177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMouseHover -->
      </class> <!-- AutomationCasesProject.TestCases.rahulShettyWebsiteCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
